# 1. Preferred tool for syncing to audio (Allowed: 'ffsubsync', 'alass', or 'ask')
audio_subsync_tool=alass

# 2. Preferred tool for syncing to another subtitle track (Allowed: 'ffsubsync', 'alass', or 'ask')
altsub_subsync_tool=alass
