# mpv_websocket
# https://github.com/kuroahna/mpv_websocket

# Setting input-ipc-server=/tmp/mpv-socket will work on both Windows and Linux
#
# On Windows, the socket will be available at \\.\pipe\tmp\mpv-socket
# On Linux, the socket will be available at /tmp/mpv-socket
#
# See: https://mpv.io/manual/stable/#options-input-ipc-server
input-ipc-server=/tmp/mpv-socket
keep-open=yes
save-position-on-quit=yes
sub-auto=fuzzy
sub-file-paths=~/Desktop/subtitles/yuruyuri3/
resume-playback=yes
watch-later-options=vid,aid,sid,volume,start,speed,sub-visibility
profile=high-quality
alang=ja
sub-font=Zen Maru Gothic
sub-bold=no
sub-font-size=45
ytdl-raw-options=sub-langs="ja.*",write-subs=,write-auto-subs=
