general {
    lock_cmd = qs ipc call lockscreen lock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on"})'  # turn on display after wake (avoids double keypress)
}

# 1. Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 2. Turn off displays 30 seconds after locking (5.5 minutes total)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on"})'
}

# 3. Suspend system after 30 minutes (optional)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
