source = ~/.config/hypr/toolkit_colors.conf

# Typography
font_family = Google Sans
font_family_monospace = JetBrainsMono Nerd Font
font_size = 11
small_font_size = 9
h1_size = 18
h2_size = 14
h3_size = 12

# Layout & Geometry
rounding_large = 12
rounding_small = 6
icon_theme = Tela-Circle
